### ISSUE TITLE
Missing csv files

### ISSUE THREAD

**Issue by me97esn** [DarknessFX/Niagara_Study#1]
I really want to test the Houdini csv stuff. But I notice that the imported csv files are not included in this repository. The paths are '/Users/mikel/Documents/projects/Epic/niagara/hip/export/csv_content_example.csv', 'D:/DFX/Downloads/StanfordScans/bunny/reconstruction/Stanford_Bunny_low.hcsv', 'C:/workbench/UE4_Study/Niagara_Study/Content/VFX/Bunny1/Stanford_Bunny.hcsv' and similar. Is it possible to add them to the repo, so it's easier to run the project?

Kind Regards
Emil

**Comment by DarknessFX** [comment]
Unfortunately I don't have the original CSV or HCSV files that you mentioned:

For csv_content_example files, they came from UE4 ContentExamples project, but they are already converted as .uasset files and I migrated them to this project.
For Stanford_Bunny files, you can find it at http://graphics.stanford.edu/data/3Dscanrep/ . I don't remember exactly but I think I used some online tool to convert PLY to CSV and then just renamed the extension to HCSV, after imported to UE4 I deleted the original files.  :/

Not everything is bad news, there are 2 HCSV raw files on the project, you can find them at: 
\Content\VFX\DepthScanning\Test.hcsv 
\Content\VFX\HCSV\Trimble.hcsv

Best regards
